#!/usr/bin/env python
import argparse
import dreampylib
import pprint

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('user', help='Your dreamhost user')
    parser.add_argument('apikey', help='Your dreamhost API key')
    args = parser.parse_args()

    connection = dreampylib.DreampyLib(args.user, args.apikey)
    if not connection.is_connected():
        raise Exception("Unable to connect")

    commands = connection.available_commands()
    pprint.pprint(commands)

if __name__ == '__main__':
    main()
